<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-FRGEB7TF" failures="1" tests="2" name="Default test" time="21.183" errors="0" timestamp="2024-07-17T02:32:03 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.087"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="8.458">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://tutorialsninja.com/demo/index.php?route=account/account] but found [https://tutorialsninja.com/demo/index.php?route=account/login]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://tutorialsninja.com/demo/index.php?route=account/account] but found [https://tutorialsninja.com/demo/index.php?route=account/login]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at SSquareIT.stepDefinition.InvalidStep.verify_the_url_of_current_page(InvalidStep.java:18)
at âœ½.verify the url of current page(file:///C:/Users/Ashwath%20K/eclipse-workspace/Framework/src/test/java/cucumber/InvalidCreds.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
